export const notionProperties = {
  title: "title",
  rich_text: "rich_text",
  number: "number",
  select: "select",
  multi_select: "multi_select",
  date: "date",
  people: "people",
  files: "files",
  checkbox: "checkbox",
  url: "url",
  email: "email",
  phone_number: "phone_number",
  formula: "formula",
  relation: "relation",
  rollup: "rollup",
  created_time: "created_time",
  created_by: "created_by",
  last_edited_time: "last_edited_time",
  last_edited_by: "last_edited_by",
} as const;

export const notionRollupFunctions = {
  count: "count",
  count_values: "count_values",
  empty: "empty",
  not_empty: "not_empty",
  unique: "unique",
  show_unique: "show_unique",
  percent_empty: "percent_empty",
  percent_not_empty: "percent_not_empty",
  sum: "sum",
  average: "average",
  median: "median",
  min: "min",
  max: "max",
  range: "range",
  earliest_date: "earliest_date",
  latest_date: "latest_date",
  date_range: "date_range",
  checked: "checked",
  unchecked: "unchecked",
  percent_checked: "percent_checked",
  percent_unchecked: "percent_unchecked",
  show_original: "show_original",
} as const;

export const notionFormulaTypes = {
  string: "string",
  number: "number",
  boolean: "boolean",
  date: "date",
  null: "null",
} as const;
